pipeline{

    agent any

    parameters {
        choice choices: ['chrome', 'firefox'], description: 'Select the browser', name: 'BROWSER'
    }

    stages{

        stage('Start Grid'){
            steps{
                 bat "docker-compose -f jenkins-ci-cd/11-runner-approach-2/grid.yaml up -d"

                //bat "docker-compose -f jenkins-ci-cd/11-runner-approach-2/grid.yaml up --scale %params.BROWSER%=2 -d"
            }
        }

        stage('Run Test'){
            steps{
                bat "docker-compose -f jenkins-ci-cd/11-runner-approach-2/test-suites.yaml up --pull=always"
                script {
                    if(fileExists('output/flight-reservation/testng-failed.xml') || fileExists('output/vendor-portal/testng-failed.xml')){
                        error('failed tests found')
                    }
                }
            }
        }

    }

    post {
        always {
            bat "docker-compose -f jenkins-ci-cd/11-runner-approach-2/grid.yaml down"
            bat "docker-compose -f jenkins-ci-cd/11-runner-approach-2/test-suites.yaml down"
            archiveArtifacts artifacts: 'jenkins-ci-cd/11-runner-approach-2/output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: 'jenkins-ci-cd/11-runner-approach-2/output/vendor-portal/emailable-report.html', followSymlinks: false
        }
    }

}