pipeline{

    agent any

    parameters {
        choice choices: ['chrome', 'firefox'], description: 'Select the browser', name: 'BROWSER'
    }

    stages{

        stage('Start Grid'){
            steps{
                 //sh "docker-compose -f jenkins-ci-cd/aws/grid.yaml up --scale=chrome=1 -d"
                 sh "docker-compose -f jenkins-ci-cd/aws/grid.yaml up --scale${params.BROWSER}=1 -d"
            }
        }

        stage('Run Test'){
            steps{
                //--pull=always es para forzar la ultima versión
                sh "docker-compose -f jenkins-ci-cd/aws/test-suites.yaml up --pull=always"
                script {
                //traemos failed.xml a la pantalla de Jenkins y de esa manera se puede comprobar los errores
                    if(fileExists('jenkins-ci-cd/aws/output/flight-reservation/testng-failed.xml') || fileExists('jenkins-ci-cd/aws/output/vendor-portal/testng-failed.xml')){
                        error('failed tests found')
                    }
                }
            }
        }

    }

    post {
        always {
            sh "docker-compose -f jenkins-ci-cd/aws/grid.yaml down"
            sh "docker-compose -f jenkins-ci-cd/aws/test-suites.yaml down"
            //se trae el resultado de la ejecución exitosa a la pantalla de Jenkins
            archiveArtifacts artifacts: 'jenkins-ci-cd/aws/output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: 'jenkins-ci-cd/aws/output/vendor-portal/emailable-report.html', followSymlinks: false
        }
    }

}