pipeline{

    agent any

    stages{

        stage('Start Grid'){
            steps{
                bat "docker-compose -f jenkins-ci-cd/10-runner-approach-1/grid.yaml up -d"
            }
        }

        stage('Run Test'){
            steps{
               bat "docker-compose -f jenkins-ci-cd/10-runner-approach-1/test-suites.yaml up --pull=always"
               script {
                   if(fileExists('jenkins-ci-cd/10-runner-approach-1/output/flight-reservation/testng-failed.xml') || fileExists('jenkins-ci-cd/10-runner-approach-1/output/vendor-portal/testng-failed.xml')){
                       error('failed tests found')
                   }
            }
        }

    }

    post {
        always {
            bat "docker-compose -f jenkins-ci-cd/10-runner-approach-1/grid.yaml down"
            bat "docker-compose -f jenkins-ci-cd/10-runner-approach-1/test-suites.yaml down"
            archiveArtifacts artifacts: 'jenkins-ci-cd/10-runner-approach-1/output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: 'jenkins-ci-cd/10-runner-approach-1/output/vendor-portal/emailable-report.html', followSymlinks: false
        }
    }

}